### ISSUE TITLE
plotsr failed on memverge with the error "Path value cannot be null"

### ISSUE THREAD

**Issue by SarahBailey1998** [Plant-Food-Research-Open/assemblyqc#184]
### Description of the bug

My memverge run of assemblyqc failed with the error "ERROR ~ Error executing process > 'PLANTFOODRESEARCHOPEN_ASSEMBLYQC:ASSEMBLYQC:FASTA_SYNTENY:PLOTSR (1)'
Caused by:
  Path value cannot be null"
As far as we could tell all of the paths specified in the params file were correct so decided to exclude plotsr from the run as a temporary work around.
For more details see the aws-utilities repo.

**Comment by GallVp** [comment]
This failure occurs because of a bug in the pipeline code where the Syri files are created in a different order and then fed to PLOTSR in the wrong order,

https://github.com/Plant-Food-Research-Open/assemblyqc/blob/01419251d52a057caa8fda571704ddc468be10d3/subworkflows/local/fasta_synteny.nf#L347

Here, `syri_tags.sort(false)` should be `syri_tags.sort(false) { it.toUpperCase() }` to match the order created  for minimap2 alignment,

https://github.com/Plant-Food-Research-Open/assemblyqc/blob/01419251d52a057caa8fda571704ddc468be10d3/subworkflows/local/fasta_synteny.nf#L276
